# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(00000C)
$foreground = rgb(E4E9FF)
$color0 = rgb(00000C)
$color1 = rgb(222D49)
$color2 = rgb(283350)
$color3 = rgb(535F84)
$color4 = rgb(5E5D84)
$color5 = rgb(8591BE)
$color6 = rgb(8591BE)
$color7 = rgb(D0D8F6)
$color8 = rgb(9197AC)
$color9 = rgb(2D3C61)
$color10 = rgb(35446B)
$color11 = rgb(6F7EAF)
$color12 = rgb(7D7CB0)
$color13 = rgb(B1C1FE)
$color14 = rgb(B1C1FE)
$color15 = rgb(D0D8F6)
